### ISSUE TITLE
Error parsing token

### ISSUE THREAD

**Issue by valentin2105** [codehakase/golang-gin#2]
Hi,

Thanks for this project, it's a very good learning way ;)

After setting up my Auth0 account, I can login to Joke App, but when try to list Jokes, nothing appear and show that on go console : 

```
Error parsing token: token contains an invalid number of segments
[GIN] 2018/04/25 - 09:13:51 | 401 |      70.616µs |             ::1 | GET      /api/jokes
```

Any idea what wrong ? 

Thanks !!

**Comment by codehakase** [comment]
Hey @valentin2105 sorry for reverting late. Confirm you have your environment variables setup properly, both on the client and server side
