### ISSUE TITLE
Error parsing token: Invalid isssuer.

### ISSUE THREAD

**Issue by voidtcg** [codehakase/golang-gin#3]
Hi there know it has to be related to scopes at this point, could you provide what scopes that you added in auth0. 
I'm using your project to learning some new techniques. 
Very convenient that I've using the exactly the same tools that you are.

I can log in no problems, just saying that I am not authorize to see the content.
But I'm the administrator/dev.

**Comment by codehakase** [comment]
@voidtcg the current project uses no scope

**Comment by voidtcg** [comment]
Ok thank Ill continue my search!

**Comment by codehakase** [comment]
@voidtcg if you still encounter an error, you can re-open this, and post terminal output
