### ISSUE TITLE
404 error when reaching '/' for static files

### ISSUE THREAD

**Issue by develaper** [codehakase/golang-gin#6]
Hi @codehakase ,
first of all I would like to thank you for your work and effort put into the tutorial. I really think it is super well explained, pointing in the right direction in every step and I was really excited about following it because you managed to make a clear explanation on how to accomplish the whole thing but I got stuck in one of the first steps just trying to display the first .html view that we have in views folder.

I found an issue related in the gin-gonic repository reporting the same problem:
[Inability to use '/' for static files](https://github.com/gin-gonic/gin/issues/75)
but I couldn't figure out how to apply any of the proposed solutions.

Also I have to add that I am trying to make it work with docker using as a base the code of:
[Gin with Go running on Docker.](https://github.com/chunghha/docker-go-gin)

In case that you want to check my code you can find it here:
https://github.com/develaper/docker-go-gingonic-react-tutorial/blob/master/src/main.go

Please let me know if you have any advise about how to proceed from here or if you need any other info.
Thanks for your time.

**Comment by develaper** [comment]
Hey @codehakase ! I am closign this issue and linking here to the solution just in case that someone finds her/himself trying to deal with this tutorial in Docker environment: https://github.com/chunghha/docker-go-gin/issues/1

**Comment by codehakase** [comment]
Thanks @develaper
